# Generated by Django 4.1.7 on 2023-03-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="date",
        ),
        migrations.RemoveField(
            model_name="location",
            name="is_active",
        ),
    ]
