# Generated by Django 4.1.7 on 2023-03-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helprequest",
            name="type",
            field=models.BooleanField(
                choices=[
                    ("FOOD", "FOOD"),
                    ("MEDICINE", "MEDICINE"),
                    ("CLOTHES", "CLOTHES"),
                    ("SHELTER", "SHELTER"),
                    ("RESCUE", "RESCUE"),
                    ("MISSING", "MISSING"),
                    ("OTHER", "OTHER"),
                ],
                default="FOOD",
                max_length=100,
            ),
        ),
    ]
