# Generated by Django 4.1.7 on 2023-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_helprequest_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helprequest",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
