# Generated by Django 4.1.7 on 2023-03-25 23:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_location_date_remove_location_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Location"
            ),
        ),
    ]
