# Generated by Django 4.1.7 on 2023-03-25 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_location_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="location",
        ),
        migrations.AddField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
